import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import TanStackProvider from '@/providers/TanStackProvider'
import { ToastContainer } from 'react-toastify'

export const metadata: Metadata = {
  title: "StalkApp",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`flex flex-col items-center`}
      >
        <ToastContainer
          position='top-right'
          autoClose={5000}
          hideProgressBar={false}
          closeOnClick
          pauseOnHover
          draggable
          theme='light'
        />
        <TanStackProvider>
          {/* <HydrationProv> */}
            {children}
          {/* </HydrationProv> */}
        </TanStackProvider>
      </body>
    </html>
  );
}
