"""add friends request model

Revision ID: 0155971ac8f1
Revises: 9e1d6a80e201
Create Date: 2025-10-15 21:06:32.384013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0155971ac8f1'
down_revision: Union[str, None] = '9e1d6a80e201'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friends_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('from_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text("timezone('utc', now())"), nullable=False),
    sa.CheckConstraint('from_user_id != user_id', name='ck_no_self_request'),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_user_id', 'user_id', name='uq_from_to_requests')
    )
    op.create_index(op.f('ix_friends_requests_from_user_id'), 'friends_requests', ['from_user_id'], unique=False)
    op.create_index(op.f('ix_friends_requests_user_id'), 'friends_requests', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_friends_requests_user_id'), table_name='friends_requests')
    op.drop_index(op.f('ix_friends_requests_from_user_id'), table_name='friends_requests')
    op.drop_table('friends_requests')
    # ### end Alembic commands ###
