"""init db

Revision ID: fc05896294c8
Revises: 
Create Date: 2025-11-22 17:44:41.907985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc05896294c8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('firstname', sa.String(length=50), nullable=True),
    sa.Column('lastname', sa.String(length=50), nullable=True),
    sa.Column('birthday', sa.DATETIME(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('timezone', sa.String(length=20), server_default='Europe/Moscow', nullable=False),
    sa.Column('subscription_type', sa.Enum('free', 'premium', 'full_premium', name='subscription_type_enum'), server_default='free', nullable=False),
    sa.Column('subscription_expired_at', sa.DATETIME(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_banned', sa.Boolean(), server_default='0', nullable=True),
    sa.Column('is_admin', sa.Boolean(), server_default='0', nullable=True),
    sa.Column('avatar', sa.String(length=255), nullable=True),
    sa.Column('password', sa.LargeBinary(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DATETIME(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('ban_list',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('admin_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DATETIME(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reason', sa.String(length=100), nullable=True),
    sa.Column('ban_status', sa.Enum('banned', 'unbanned', name='ban_status_enum'), server_default='unbanned', nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ban_list_admin_id'), 'ban_list', ['admin_id'], unique=False)
    op.create_index(op.f('ix_ban_list_id'), 'ban_list', ['id'], unique=True)
    op.create_index(op.f('ix_ban_list_user_id'), 'ban_list', ['user_id'], unique=False)
    op.create_table('friends_list',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('friend_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DATETIME(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['friend_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'friend_id', name='uq_user_friend_constraint')
    )
    op.create_index(op.f('ix_friends_list_id'), 'friends_list', ['id'], unique=True)
    op.create_table('friends_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('from_user_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DATETIME(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('from_user_id != user_id', name='ck_no_self_request'),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_user_id', 'user_id', name='uq_from_to_requests')
    )
    op.create_index(op.f('ix_friends_requests_from_user_id'), 'friends_requests', ['from_user_id'], unique=False)
    op.create_index(op.f('ix_friends_requests_id'), 'friends_requests', ['id'], unique=True)
    op.create_index(op.f('ix_friends_requests_user_id'), 'friends_requests', ['user_id'], unique=False)
    op.create_table('posts',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('content', sa.String(length=500), nullable=True),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('updated_at', sa.DATETIME(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DATETIME(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posts_user_id'), 'posts', ['user_id'], unique=False)
    op.create_table('tokens',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token', sa.String(length=400), nullable=False),
    sa.Column('created_at', sa.DATETIME(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expire_at', sa.DATETIME(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tokens_token'), 'tokens', ['token'], unique=False)
    op.create_index(op.f('ix_tokens_user_id'), 'tokens', ['user_id'], unique=False)
    op.create_table('post_comments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('post_id', sa.String(length=36), nullable=False),
    sa.Column('content', sa.String(length=500), nullable=True),
    sa.Column('updated_at', sa.DATETIME(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DATETIME(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_comments_id'), 'post_comments', ['id'], unique=True)
    op.create_index(op.f('ix_post_comments_post_id'), 'post_comments', ['post_id'], unique=False)
    op.create_index(op.f('ix_post_comments_user_id'), 'post_comments', ['user_id'], unique=False)
    op.create_table('post_images',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('post_id', sa.String(length=36), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DATETIME(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_images_id'), 'post_images', ['id'], unique=True)
    op.create_index(op.f('ix_post_images_post_id'), 'post_images', ['post_id'], unique=False)
    op.create_table('comment_images',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('comment_id', sa.String(length=36), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DATETIME(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['post_comments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comment_images_comment_id'), 'comment_images', ['comment_id'], unique=False)
    op.create_index(op.f('ix_comment_images_id'), 'comment_images', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comment_images_id'), table_name='comment_images')
    op.drop_index(op.f('ix_comment_images_comment_id'), table_name='comment_images')
    op.drop_table('comment_images')
    op.drop_index(op.f('ix_post_images_post_id'), table_name='post_images')
    op.drop_index(op.f('ix_post_images_id'), table_name='post_images')
    op.drop_table('post_images')
    op.drop_index(op.f('ix_post_comments_user_id'), table_name='post_comments')
    op.drop_index(op.f('ix_post_comments_post_id'), table_name='post_comments')
    op.drop_index(op.f('ix_post_comments_id'), table_name='post_comments')
    op.drop_table('post_comments')
    op.drop_index(op.f('ix_tokens_user_id'), table_name='tokens')
    op.drop_index(op.f('ix_tokens_token'), table_name='tokens')
    op.drop_table('tokens')
    op.drop_index(op.f('ix_posts_user_id'), table_name='posts')
    op.drop_table('posts')
    op.drop_index(op.f('ix_friends_requests_user_id'), table_name='friends_requests')
    op.drop_index(op.f('ix_friends_requests_id'), table_name='friends_requests')
    op.drop_index(op.f('ix_friends_requests_from_user_id'), table_name='friends_requests')
    op.drop_table('friends_requests')
    op.drop_index(op.f('ix_friends_list_id'), table_name='friends_list')
    op.drop_table('friends_list')
    op.drop_index(op.f('ix_ban_list_user_id'), table_name='ban_list')
    op.drop_index(op.f('ix_ban_list_id'), table_name='ban_list')
    op.drop_index(op.f('ix_ban_list_admin_id'), table_name='ban_list')
    op.drop_table('ban_list')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
