"""update user model, add friends list table

Revision ID: 1f043ce96c14
Revises: 522bbc7022eb
Create Date: 2025-10-12 17:54:15.521247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f043ce96c14'
down_revision: Union[str, None] = '522bbc7022eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('friends_list', sa.Column('added_at', sa.TIMESTAMP(timezone=True), server_default=sa.text("timezone('utc', now())"), nullable=False))
    op.create_unique_constraint('uq_user_friend_constraint', 'friends_list', ['user_id', 'friend_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_friend_constraint', 'friends_list', type_='unique')
    op.drop_column('friends_list', 'added_at')
    # ### end Alembic commands ###
